Algoritmo "semnome"
Var

  volume, raio, altura: real
  
Inicio

    escreva ("digite a altura da lata de óleo sem o uso do 'cm': ")
      leia (altura)
      escreval("---------------------------------------------------")
    escreva ("digite o raio da lata de óleo : ")
      leia (raio)
      
    volume<- pi * raio^2 * altura
    escreval ("-----------------------------------------")
    
    escreval ("o volume da lata de óleo é de: ", volume)
Fimalgoritmo