Algoritmo "semnome"

Var

vt1: vetor [0..14] de inteiro
vt2: vetor [0..14] de inteiro
contador: inteiro

Inicio

 para contador de 0 ate 14 faca
   escreva ("digite 14 números diferentes: ")
    leia (vt1[contador])
 fimpara

 escolha contador
  caso (contador mod 2 = 0)
   escreval ("esses numeros sao pares")
  caso (contador mod 1 = o)
   escreval ("esses numeros sao impares")
fimescolha
Fimalgoritmo